GET http://localhost:8000/ HTTP/1.1
### GENERATE ERROR 404
GET http://localhost:8000/api/task HTTP/1.1
Content-Type: application/json

{
  "error": true
}
### GET ALL TASKS
GET http://localhost:8000/api/task HTTP/1.1
### GET TASK BY ID
GET http://localhost:8000/api/task/1 HTTP/1.1
### CREATE TASK
POST http://localhost:8000/api/task HTTP/1.1
Content-Type: application/json

{
  "title": "Task 2",
  "description": "Task 2 description",
  "studentId": 1
}
### UPDATE TASK
PUT http://localhost:8000/api/task/1 HTTP/1.1
Content-Type: application/json

{
  "title": "Task 1",
  "description": "Task 1 description",
  "studentId": 1,
}
### DELETE TASK
DELETE http://localhost:8000/api/task/1 HTTP/1.1
### CREATE STUDENT
POST http://localhost:8000/api/student HTTP/1.1
Content-Type: application/json

{
  "firstName": "Student 1",
  "lastName": "Student 1 last name",
  "age": 20,
  "grade": 10
}